module.exports = {
  "NIFTY BANK": [
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "SBIN.NS",
    "AXISBANK.NS",
    "KOTAKBANK.NS",
    "BANKBARODA.NS",
    "PNB.NS",
    "CANBK.NS",
    "INDUSINDBK.NS",
    "IDFCFIRSTB.NS",
    "AUBANK.NS",
    "FEDERALBNK.NS",
  ],

  "NIFTY IT": [
    "TCS.NS",
    "INFY.NS",
    "HCLTECH.NS",
    "WIPRO.NS",
    "TECHM.NS",
    "LTTS.NS",
    "PERSISTENT.NS",
    "COFORGE.NS",
    "MPHASIS.NS",
    "OFSS.NS",
  ],
  "NIFTY FMCG": [
    "HINDUNILVR.NS",
    "ITC.NS",
    "NESTLEIND.NS",
    "BRITANNIA.NS",
    "DABUR.NS",
    "MARICO.NS",
    "GODREJCP.NS",
    "COLPAL.NS",
    "TATACONSUM.NS",
    "PIDILITIND.NS",
  ],
  "NIFTY PHARMA": [
    "SUNPHARMA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "CIPLA.NS",
    "GLENMARK.NS",
    "AUROPHARMA.NS",
    "ALKEM.NS",
    "TORNTPHARM.NS",
    "BIOCON.NS",
    "IPCALAB.NS",
  ],
  "NIFTY METAL": [
    "HINDALCO.NS",
    "TATASTEEL.NS",
    "JSWSTEEL.NS",
    "VEDL.NS",
    "COALINDIA.NS",
    "NMDC.NS",
    "SAIL.NS",
    "HINDZINC.NS",
    "NATIONALUM.NS",
    "JINDALSTEL.NS",
  ],
  "NIFTY AUTO": [
    "MARUTI.NS",
    "M&M.NS",
    "TMPV.NS",
    "BAJAJ-AUTO.NS",
    "EICHERMOT.NS",
    "HEROMOTOCO.NS",
    "ASHOKLEY.NS",
    "TVSMOTOR.NS",
    "BAJAJFINSV.NS",
    "BOSCHLTD.NS",
  ],
  "NIFTY ENERGY": [
    "RELIANCE.NS",
    "NTPC.NS",
    "POWERGRID.NS",
    "IOC.NS",
    "BPCL.NS",
    "GAIL.NS",
    "ONGC.NS",
    "ADANIPOWER.NS",
    "TATAPOWER.NS",
    "HINDPETRO.NS",
  ],
  "NIFTY REALTY": [
    "DLF.NS",
    "GODREJPROP.NS",
    "OBEROIRLTY.NS",
    "PRESTIGE.NS",
    "Sobha.NS",
    "BRIGADE.NS",
    "PHOENIXLTD.NS",
    "Lodha.NS",
    "MAHLIFE.NS",
  ],
  "NIFTY 50": [
    "RELIANCE.NS",
    "TCS.NS",
    "HDFCBANK.NS",
    "INFY.NS",
    "HINDUNILVR.NS",
    "ICICIBANK.NS",
    "KOTAKBANK.NS",
    "SBIN.NS",
    "ITC.NS",
    "AXISBANK.NS",
  ],
  "NIFTY PSU BANK": [
    "PNB.NS",
    "BANKBARODA.NS",
    "CANBK.NS",
    "IDFCFIRSTB.NS",
    "INDUSINDBK.NS",
    "FEDERALBNK.NS",
    "SBIN.NS",
    "BANKBARODA.NS",
    "UCOBANK.NS",
    "CENTRALBK.NS",
  ],
  "NIFTY FIN SERVICES": [
    "HDFCBANK.NS",
    "ICICIBANK.NS",
    "KOTAKBANK.NS",
    "SBIN.NS",
    "AXISBANK.NS",
    "BAJFINANCE.NS",
    "BAJAJFINSV.NS",
    "MUTHOOTFIN.NS",
    "ICICIPRULI.NS",
  ],
};
